"""Initial migration

Revision ID: 4e1d4740eb71
Revises: 
Create Date: 2025-01-12 10:39:56.542398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e1d4740eb71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
   # Cria a tabela User primeiro
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=150), nullable=False),
        sa.Column('password', sa.String(length=200), nullable=False),
        sa.Column('role', sa.String(length=50), nullable=False),
        sa.Column('is_approved', sa.Boolean(), nullable=True),
        sa.Column('is_admin', sa.Boolean(), nullable=True),
        sa.Column('name', sa.String(length=150), nullable=True),
        sa.Column('age', sa.Integer(), nullable=True),
        sa.Column('phone', sa.String(length=15), nullable=True),
        sa.Column('address', sa.String(length=200), nullable=True),
        sa.Column('mensalidade_paga', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
    )

    # Cria a tabela Turma depois
    op.create_table(
        'turma',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=150), nullable=False),
        sa.Column('professor_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['professor_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Cria a tabela Pagamento por último
    op.create_table(
        'pagamento',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('mes', sa.String(length=20), nullable=False),
        sa.Column('pago', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagamento')
    op.drop_table('user')
    op.drop_table('turma')
    # ### end Alembic commands ###
