"""Recriar migrações

Revision ID: 5b52dcbc3474
Revises: ec9e53bbe8fb
Create Date: 2025-01-13 14:04:21.644696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b52dcbc3474'
down_revision = 'ec9e53bbe8fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico_matricula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('data_acao', sa.DateTime(), nullable=False),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('data_nascimento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('sexo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('profissao', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('endereco', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('numero_endereco', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('contato_1', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('contato_2', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('contato_emergencia', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('nome_contato_emergencia', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('antecedentes_cirurgicos', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tratamentos_medicamentosos', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('antecedentes_alergicos', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('funcionamento_intestino', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pratica_atividade_fisica', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('indicacoes_observacoes', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('indicacoes_observacoes')
        batch_op.drop_column('pratica_atividade_fisica')
        batch_op.drop_column('funcionamento_intestino')
        batch_op.drop_column('antecedentes_alergicos')
        batch_op.drop_column('tratamentos_medicamentosos')
        batch_op.drop_column('antecedentes_cirurgicos')
        batch_op.drop_column('nome_contato_emergencia')
        batch_op.drop_column('contato_emergencia')
        batch_op.drop_column('contato_2')
        batch_op.drop_column('contato_1')
        batch_op.drop_column('cep')
        batch_op.drop_column('estado')
        batch_op.drop_column('cidade')
        batch_op.drop_column('bairro')
        batch_op.drop_column('numero_endereco')
        batch_op.drop_column('endereco')
        batch_op.drop_column('profissao')
        batch_op.drop_column('sexo')
        batch_op.drop_column('data_nascimento')
        batch_op.drop_column('email')

    op.drop_table('historico_matricula')
    # ### end Alembic commands ###
