"""Adicionar tabela HistoricoMatricula

Revision ID: 96363940f772
Revises: f8579f0fe3f9
Create Date: 2025-01-13 00:30:56.047821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96363940f772'
down_revision = 'f8579f0fe3f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensalidade', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['professor_id'], ['id'])
        batch_op.create_foreign_key(None, 'turma', ['turma_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensalidade', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
