"""Add many-to-many relationship between User and Turma

Revision ID: c4f0a066c4a8
Revises: f7976d8cc046
Create Date: 2025-01-12 21:47:58.977216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4f0a066c4a8'
down_revision = 'f7976d8cc046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_ibfk_1', type_='foreignkey')
        batch_op.drop_column('name')
        batch_op.drop_column('mensalidade_paga')
        batch_op.drop_column('turma_id')
        batch_op.drop_column('address')
        batch_op.drop_column('age')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=15), nullable=True))
        batch_op.add_column(sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('turma_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mensalidade_paga', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=150), nullable=True))
        batch_op.create_foreign_key('user_ibfk_1', 'turma', ['turma_id'], ['id'])

    # ### end Alembic commands ###
