"""Adicionar tabela historico_matricula

Revision ID: ec9e53bbe8fb
Revises: 96363940f772
Create Date: 2025-01-13 00:57:07.001096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9e53bbe8fb'
down_revision = '96363940f772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico_matricula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('data_acao', sa.DateTime(), nullable=False),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_matricula')
    # ### end Alembic commands ###
