"""Correção do relacionamento Turma-User

Revision ID: f7976d8cc046
Revises: 4e1d4740eb71
Create Date: 2025-01-12 10:46:35.293526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7976d8cc046'
down_revision = '4e1d4740eb71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turma_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'turma', ['turma_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('turma_id')

    # ### end Alembic commands ###
