"""Adicionar modelo de mensalidades e ajustar contas

Revision ID: f8579f0fe3f9
Revises: 44de0d8b98ed
Create Date: 2025-01-12 23:06:26.788595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8579f0fe3f9'
down_revision = '44de0d8b98ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensalidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_matricula', sa.Date(), nullable=False, server_default='2023-01-01'))
        batch_op.alter_column('data_matricula', server_default=None)  # Remove o valor padrão após a criação, se necessário
       
        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensalidade', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('data_matricula')
        batch_op.drop_column('professor_id')
        batch_op.drop_column('turma_id')

    # ### end Alembic commands ###
