"""empty message

Revision ID: fa15b9aacbce
Revises: 5b52dcbc3474
Create Date: 2026-02-07 15:43:52.710110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa15b9aacbce'
down_revision = '5b52dcbc3474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativa', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.drop_column('ativa')

    # ### end Alembic commands ###
